CREATE TABLE `mano_mmf_price` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `line_hash` char(64) NOT NULL COMMENT 'Excel 行内容 SHA256',
  `source_brand` varchar(32) DEFAULT NULL COMMENT '品牌',
  `market_region` varchar(64) NOT NULL DEFAULT '' COMMENT '市场区域（按账单文件名映射）',
  `seller_account_id` int NOT NULL COMMENT 'SELLER_ACCOUNT_ID',
  `seller_id` bigint NOT NULL COMMENT 'SELLER_ID',
  `seller_name` varchar(64) NOT NULL COMMENT 'SELLER_NAME',
  `platform` char(2) NOT NULL COMMENT '销售站点，如 FR/ES/IT/DE',
  `ean` varchar(20) DEFAULT NULL COMMENT 'EAN',
  `seller_sku` varchar(64) NOT NULL COMMENT 'SELLER_SKU',
  `warehouse_sku` varchar(100) NOT NULL DEFAULT '',
  `mm_id` varchar(20) DEFAULT NULL COMMENT 'MM_ID',
  `length_cm` decimal(8,2) DEFAULT NULL COMMENT '长(cm)',
  `width_cm` decimal(8,2) DEFAULT NULL COMMENT '宽(cm)',
  `height_cm` decimal(8,2) DEFAULT NULL COMMENT '高(cm)',
  `weight_kg` decimal(8,3) DEFAULT NULL COMMENT '重量(kg)',
  `dispatch_warehouse` varchar(20) DEFAULT NULL COMMENT '发货仓',
  `destination_platform` char(2) DEFAULT NULL COMMENT '目的站点',
  `dispatch_fee_vat_exc` decimal(10,4) NOT NULL COMMENT '运费(未税)',
  `dispatch_date` date DEFAULT NULL COMMENT '最近发货日期',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hash` (`line_hash`),
  KEY `idx_sku` (`seller_sku`),
  KEY `idx_mmid` (`mm_id`),
  KEY `idx_ean` (`ean`),
  KEY `seller_name` (`seller_name`),
  KEY `idx_platform_sku` (`platform`,`seller_sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ManoMano Fulfillment Price';